# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6411037853ac104b1e2584a31ebee25cc338a6db024b619bf75179aa5fdbf42d042de1aee1f010ec7090cbaaa14dad8cc47ca108eca66e6df9846970ae23d660

test:
  secret_key_base: 24974f51c5c62770b042d6fec4f8a5f2d7f7d57738177765e35c4481f8981e4e1ce25dde207940f83d349fd0cd6c13c9f1a86d0363ba19974fdb6f87432c1d53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
